WebApp1/Controllers/BikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vroom.AppDbContext;
using vroom.Models;
using vroom.Models.ViewModels;

namespace vroom.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class BikeController : Controller
    {

        private readonly VroomDbContext _db;

        [BindProperty]
        public BikeViewModel BikeViewModel { get; set; }

        public BikeController(VroomDbContext db)
        {
            _db = db;
            BikeViewModel = new BikeViewModel()
            {
                Makes = _db.Makes.ToList(),
                Models = _db.Models.ToList(),
                Bike = new Models.Bike()
            };

        }
        public IActionResult Index()
        {
            var bikes = _db.Bikes.Include(m => m.Make).Include(m => m.Model);
            return View(bikes.ToList());
        }

        public IActionResult Create()
        {
            return View(BikeViewModel);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost()
        {
            if (ModelState.IsValid)
            {
                _db.Bikes.Add(BikeViewModel.Bike);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(BikeViewModel);
        }

        //[HttpGet]
        //public IActionResult Edit(int id)
        //{
        //    var model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
        //    ModelViewModel.Model = model;
        //    if (model is null)
        //    {
        //        return NotFound();
        //    }
        //    return View(ModelViewModel);
        //}

        //[HttpPost]
        //public IActionResult Edit()
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Update(ModelViewModel.Model);
        //        _db.SaveChanges();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(ModelViewModel);
        //}

        //[HttpPost]
        //public IActionResult Delete(int id)
        //{
        //    var model = _db.Models.Find(id);
        //    if (model is null)
        //    {
        //        return NotFound();
        //    }
        //    _db.Models.Remove(model);
        //    _db.SaveChanges();
        //    return RedirectToAction(nameof(Index));
        //}


    }
}

WebApp1/Controllers/MakeController.cs
using System;
using vroom.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using vroom.AppDbContext;
using Microsoft.AspNetCore.Authorization;

namespace vroom.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class MakeController : Controller
    {
        private readonly VroomDbContext _db;

        public MakeController(VroomDbContext db)
        {
            _db = db;

        }

        public IActionResult Index()
        {
            return View(_db.Makes.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                _db.Add(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(make);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var make = _db.Makes.Find(id);
            if (make is null)
            {
                return NotFound();
            }
            _db.Makes.Remove(make);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var make = _db.Makes.Find(id);
            if (make is null)
            {
                return NotFound();
            }
            return View(make);
        }

        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _db.Update(make);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(make);
        }
    }
}

WebApp1/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using vroom.AppDbContext;
using vroom.Models;
using vroom.Models.ViewModels;

namespace vroom.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class ModelController : Controller
    {

        private readonly VroomDbContext _db;

        [BindProperty]
        public ModelViewModel ModelViewModel { get; set; }

        public ModelController(VroomDbContext db)
        {
            _db = db;
            ModelViewModel = new ModelViewModel()
            {
                Makes = _db.Makes.ToList(),
                Model = new Models.Model()
            };

        }
        public IActionResult Index()
        {
            var model = _db.Models.Include(m => m.Make);
            return View(model);
        }

        public IActionResult Create()
        {
            return View(ModelViewModel);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost(Model model)
        {
            if (ModelState.IsValid)
            {
                _db.Models.Add(ModelViewModel.Model);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(ModelViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var model = _db.Models.Include(m => m.Make).SingleOrDefault(m => m.Id == id);
            ModelViewModel.Model = model;
            if (model is null)
            {
                return NotFound();
            }
            return View(ModelViewModel);
        }

        [HttpPost]
        public IActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                _db.Update(ModelViewModel.Model);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(ModelViewModel);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var model = _db.Models.Find(id);
            if (model is null)
            {
                return NotFound();
            }
            _db.Models.Remove(model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


    }
}

WebApp1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - vroom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/d4ea7fe337.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">vroom</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin") | User.IsInRole("Executive"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Master
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Make" asp-action="Index">Makes</a>
                                    <a class="dropdown-item" asp-controller="Model" asp-action="Index">Models</a>
                                    <a class="dropdown-item" asp-controller="Bike" asp-action="Index">Bikes</a>
                                </div>
                            </li>
                        }
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - vroom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp1/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

                    <td class="text-right">
                        <div class="btn-group" role="group">
                            <form method="get" action="Edit">
                                <button type="submit" class="btn btn-primary" asp-route-id="@Model" asp-action="Edit"><i class="far fa-edit"></i></button>
                            </form>
                            <form method="post" action="Delete">
                                <button onclick="if (!confirm('Are you sure you wish to delete this item?')) { return false }" type="submit" class="btn btn-danger rounded-0" asp-route-id="@Model" asp-action="Delete"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </div>
                    </td>